from enum import Enum

class AppStatus(str, Enum):
    RESUME_RECEIVED = "RESUME_RECEIVED"
    RESUME_GRADED = "RESUME_GRADED"
    ASSESSMENT_PENDING = "ASSESSMENT_PENDING"
    ASSESSMENT_GRADED = "ASSESSMENT_GRADED"
    ASSESSMENT_TAKEN = "ASSESSMENT_TAKEN", 
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_TAKEN = "INTERVIEW_TAKEN"
    INTERVIEW_GRADED = "INTERVIEW_GRADED"
    REJECTED = "REJECTED"
    HIRED = "HIRED"



